### ISSUE TITLE
The results of reproduction.

### ISSUE THREAD

**Issue by guangqian-guo** [mrwu-mac/ControlMLLM#24]
Hi authors, I reproduced the results following the README, but found that the results are quite different from those in the paper. Could you help me analyze the reason?

```bash
sh task/ROC/llava_roc.sh
python task/ROC/eval.py --pred_file='outputs/llava_7b_roc_box.json' --set='test'
```
The results I got are:
```
1548it [00:00, 178800.50it/s]
Baseline ---> Acc:54.651%
1548it [00:00, 192749.97it/s]
Ours ---> Acc:54.716%
```

**Comment by guangqian-guo** [comment]
Sorry, I modified the original code, which caused this problem. It is solved now. I will close this issue

**Comment by freya9933** [comment]
Hi, may I ask where the modification was made? I am using the latest version of the code, but still cannot obtain the results as described in the paper.

**Comment by freya9933** [comment]
> Sorry, I modified the original code, which caused this problem. It is solved now. I will close this issue

Hi, may I ask where the modification was made? I am using the latest version of the code, but still cannot obtain the results as described in the paper.
